#!/bin/sh

echo "Running docgenerator..."
python docgenerator.py
echo "Updating commit..."

git add docs/generated/tuners.md
git add docs/generated/graph_filters.md
git add docs/generated/measures.md
git add docs/generated/postprocessors.md
git add docs/generated/datasets.md